* LeeSin's vanilla Emacs
** Features
1. Modularization
2. Write From scratch
3. Manage the code by org mode
** Build
Use the following command to use my configuration.
#+BEGIN_src sh
  mv ~/.emacs.d ~/.emacs.d.bak
  git clone https://github.com/endlesspeak/.emacs.d ~
  make generate
#+END_src

If you are using =Gentoo Linux= you should check the following things:
1. check the use options:
   #+BEGIN_SRC conf
     app-editors/emacs acl alsa cairo dbus dynamic-loading gfile gmp gpm gsettings gui gzip-el inotify jpeg json kerberos lcms libxml2 png source ssl systemd threads xft xpm zlib
   #+END_SRC
2. Install =emacs-daemon= and =emacs-common=

** Dependency
部分包是直接从 =github= 上下载的，需要手动克隆。（目前不打算使用 =quelpa= 包）
1. doom-snippets
   ~git clone https://github.com/doomemacs/snippets~
2. color-rg
   1. ~git clone https://github.com/manateelazycat/color-rg~
   2. 如不习惯使用 =package.el= ，可根据 =init-vertico.org= 中的笔记进行修改
3. citre
   安装 =ctags= ，注意 =windows= 平台上不要安装 =clang= 版本的。仓库 https://github.com/universal-ctags/ctags-win32
4. catppuccin (optional)
   根据 =init-ui.org= 中的笔记进行修改

** Load From Anywhere
为了支持从任何目录加载该配置文件（例如从 U 盘加载配置文件）作了一定的适应性修改，这可能影响加载速度或带来不稳定性。其中：
1. 使用全局变量 =user-init-file= =user-emacs-directory= 和 =package-user-directory= 记录配置文件目录和插件下载目录
2. 在 =use-package= 中，任何的 ~:load-path~ 参数都需要一个路径字符串或一个代表路径的符号，在目前情况下，可以使用 =lambda= 函数动态实现
3. 从其他位置加载配置文件，需要在命令前使用 =env= 指明环境变量，例如在 =windows= 上可以编写 bat 文件：
   #+begin_src bat
     @echo off
     set "HOME=X:\path\to\dir"
     start /b "Emacs" "X:\path\to\emacs\bin\runemacs.exe" %*
   #+end_src
   在 =linux= 上可以使用命令 ~env HOME=/path/to/dir emacs~
** Faster Launching
现在可以在 =emacs= 启动后运行 ~eval-expression~ ，通过 =byte-compile= 加快加载速度。
由于 =init-package.el= 编译字节码出错，已对项目结构进行重构，以使其仅编译 =etc= 和 =lang= 文件夹。
也可以单独在 =init-package.el= 上设置 ~no-byte-compile t~ 。
#+begin_src emacs-lisp
  (byte-recompile-directory "lisp/etc" 0)
  (byte-recompile-directory "lisp/lang" 0)
#+end_src
其中， =0= 表示编译时不需要进行确认。
** Note
1. No guarantee for stablity
2. Update extremely slow
** Reference
Refer these repos to obtain config files.
1. [[https://github.com/nasyxx/emacs.d/][Nasyxx]]
2. [[https://remacs.cc/posts/][remacs]]
3. [[https://github.com/seagle0128/.emacs.d][Centaur]]
4. [[https://github.com/MatthewZMD/.emacs.d][MatthewZMD]]
5. [[https://github.com/redguardtoo/emacs.d][Redguard]]
6. [[https://github.com/evanmeek/.emacs.d][Evanmeek]]
7. [[https://github.com/springhan/.emacs.d][SpringHan]]
8. [[https://github.com/cabins/.emacs.d][Cabins]]
9. [[https://github.com/7ym0n/dotfairy][7ym0n]]

